const KEY = 'carelens.analysis';

function formatDateValue(value) {
  if (!value) return null;

  const date = new Date(value);

  if (Number.isNaN(date.getTime())) {
    return value;
  }

  return date.toISOString();
}

function createDiscrepancyId(discrepancy, index) {
  return (
    discrepancy.id ??
    `${discrepancy.type ?? 'discrepancy'}-${index}`
  );
}

function normalizeEvidence(evidence = []) {
  if (!Array.isArray(evidence)) {
    return [];
  }

  return evidence.map((item, index) => ({
    id: item.id ?? `evidence-${index}`,
    document:
      item.document ??
      item.fileName ??
      item.title ??
      'Supporting document',
    page: item.page ?? item.pageNumber ?? null,
    quote: item.quote ?? item.content ?? '',
    content: item.content ?? item.quote ?? '',
    score: item.score ?? item.similarity ?? null,
    metadata: item.metadata ?? {},
  }));
}

function normalizeAnalysisResponse(response) {
  const bill = response?.bill ?? {};
  const validation = response?.validation ?? {};
  const aiAnalysis = response?.analysis ?? {};

  const evidence = normalizeEvidence(
    response?.evidence ?? []
  );

  const rawDiscrepancies =
    aiAnalysis.discrepancies ??
    validation.discrepancies ??
    [];

  const discrepancies = rawDiscrepancies.map(
    (discrepancy, index) => ({
      ...discrepancy,

      id: createDiscrepancyId(
        discrepancy,
        index
      ),

      billedValue:
        discrepancy.billedValue ??
        discrepancy.billedAmount ??
        null,

      evidence:
        discrepancy.evidence ?? [],

      evidenceId:
        discrepancy.evidenceId ??
        discrepancy.evidence?.[0]?.id ??
        evidence[0]?.id ??
        null,
    })
  );

  const total =
    bill.total ??
    bill.subtotal ??
    0;

  const flaggedAmount = discrepancies.reduce(
    (sum, discrepancy) =>
      sum +
      Number(
        discrepancy.billedValue ??
        discrepancy.billedAmount ??
        0
      ),
    0
  );

  return {
    /*
     * Original backend response
     *
     * Keeping this makes it possible to access
     * the raw backend data later without another
     * API request.
     */
    rawResponse: response,

    /*
     * General analysis information
     */
    status:
      aiAnalysis.overallStatus ??
      validation.status ??
      'INSUFFICIENT_EVIDENCE',

    overallStatus:
      aiAnalysis.overallStatus ??
      validation.status ??
      'INSUFFICIENT_EVIDENCE',

    summary:
      aiAnalysis.summary ??
      validation.summary ??
      '',

    explanation:
      aiAnalysis.explanation ??
      '',

    knowledgeBase:
      'CareLens analysis based on extracted bill data, deterministic validation, and available supporting documentation.',

    /*
     * Bill information
     */
    hospital:
      bill.vendor ??
      'Hospital',

    billReference:
      bill.billNumber ??
      '—',

    admittedOn:
      formatDateValue(
        bill.admittedOn ??
        bill.billDate
      ),

    dischargedOn:
      formatDateValue(
        bill.dischargedOn ??
        bill.billDate
      ),

    payer:
      bill.payer ??
      null,

    /*
     * Summary values expected by BillSummary
     */
    summaryData: {
      total,
      verifiedAmount:
        validation.status === 'PASS'
          ? total
          : Math.max(
              0,
              total - flaggedAmount
            ),
      underReviewAmount:
        validation.status === 'PASS'
          ? 0
          : flaggedAmount,

      chargeCount:
        Array.isArray(bill.items)
          ? bill.items.length
          : 0,
    },

    /*
     * Keep the original bill object
     */
    bill,

    /*
     * Validation
     */
    validation,

    /*
     * Discrepancies
     */
    discrepancies,

    /*
     * Evidence
     */
    evidence,

    /*
     * Questions generated by the AI
     */
    questionsToAsk:
      aiAnalysis.questionsToAsk ?? [],

    /*
     * File information
     */
    file:
      response?.file ?? null,
  };
}

export function saveAnalysis(response) {
  try {
    const normalized =
      normalizeAnalysisResponse(response);

    sessionStorage.setItem(
      KEY,
      JSON.stringify(normalized)
    );

    return normalized;
  } catch {
    return null;
  }
}

export function loadAnalysis() {
  try {
    const stored =
      sessionStorage.getItem(KEY);

    if (!stored) {
      return null;
    }

    return JSON.parse(stored);
  } catch {
    return null;
  }
}

export function clearAnalysis() {
  try {
    sessionStorage.removeItem(KEY);
  } catch {
    // Ignore storage errors.
  }
}

export { normalizeAnalysisResponse };